author:      "Josephine Ceria"
version:     "0001/07/Feb/2022"
copyright:   "2022"
title:       "OS221 -- Operating Systems -- 2021-2"
githublink:  "https://github.com/josephineceria/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
